title: Gnerate
description: >- 
  CLI that reduces boilerplate in projects
baseurl: "/"
url: "http://dylanpaulus.com"

permalink: pretty

defaults:
- scope:
    path: _docs
    type: pages
  values:
    layout: docs
    sectionid: docs

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: compressed
