title: Gnerate
description: >- 
  CLI that reduces boilerplate in projects
baseurl: "/"
url: "https://ganderzz.github.io/gnerate"

permalink: pretty

defaults:
- scope:
    path: docs
    type: pages
  values:
    layout: docs
    sectionid: docs

markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
